name: dvran express

on:
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      # - run: npm test
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Deploy to server
      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # 使用 SSH 连接到服务器并部署
          ssh -i private_key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP <<EOF
            cd $DEPLOY_DIR || exit 1
            git pull origin main || exit 2  # 拉取最新代码
            npm install || exit 3  # 安装依赖
            # 找到并杀掉 ts-node 进程
            # PID=$(pgrep -f "ts-node index.ts") 
            # if [[ -n "$PID" ]]; then
            #   kill -9 $PID || exit 4
            #   while pgrep -f "ts-node index.ts" >/dev/null; do
            #     sleep 0.5  # 每 0.5 秒检查一次进程是否还在
            #   done
            # fi
            # 启动新的
            bash /www/server/nodejs/vhost/scripts/dvran_express.sh || exit 4
            # pm2 restart dvran-express || pm2 start npm --name dvran-express -- run start || exit 4  # 使用 pm2 重启应用
          EOF